name: Terraform Dev CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./day-7-webapp-architecture/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="admin_ip=${{ secrets.ADMIN_IP }}" \
            -var="admin_username=${{ secrets.ADMIN_USERNAME }}" \
            -var="admin_password=${{ secrets.ADMIN_PASSWORD }}" \
            -var="vnet_cidr=10.0.0.0/16" \
            -var="web_subnet_cidr=10.0.1.0/24" \
            -var="app_subnet_cidr=10.0.2.0/24" \
            -var="db_subnet_cidr=10.0.3.0/24" \
            -var="resource_group_name=TemDevOps-Dev"
      

      

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="admin_ip=${{ secrets.ADMIN_IP }}" \
            -var="admin_username=${{ secrets.ADMIN_USERNAME }}" \
            -var="admin_password=${{ secrets.ADMIN_PASSWORD }}"
        timeout-minutes: 20
      
      
      
      
      

